---
- hosts: all
  pre_tasks:
    - name: refresh apt cache
      apt: update_cache=yes cache_valid_time=3600

- hosts: db
  roles:
    - role: retr0h.demeter
    - role: ANXS.postgresql
      postgresql_databases:
        - name: demeter
      postgresql_users:
        - name: demeter_user
          pass: pass
          encrypted: no
      postgresql_user_privileges:
        - name: demeter
          db: demeter
          priv: "ALL"
      postgresql_listen_addresses:
        - localhost
  tasks:
    - apt: name={{ item }}
      with_items:
        - python-pip
        - python-dev
        - libpq-dev
        - git
        - make
    - pip: name=tox
